use anyhow::{bail, Context, Result};
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

pub fn run(repo_root: &Path, version: &str) -> Result<()> {
    let dist = repo_root.join("dist");
    let arm64_sha = sha256(&dist.join("jekko-linux-arm64.tar.gz"))?;
    let x64_sha = sha256(&dist.join("jekko-linux-x64.tar.gz"))?;
    let mac_x64_sha = sha256(&dist.join("jekko-darwin-x64.zip"))?;
    let mac_arm64_sha = sha256(&dist.join("jekko-darwin-arm64.zip"))?;

    update_aur(repo_root, version, &arm64_sha, &x64_sha)?;
    update_homebrew(
        repo_root,
        version,
        &mac_x64_sha,
        &mac_arm64_sha,
        &arm64_sha,
        &x64_sha,
    )?;
    Ok(())
}

const EMPTY_SUBVER_DEFAULT: String = String::new();

fn update_aur(repo_root: &Path, version: &str, arm64_sha: &str, x64_sha: &str) -> Result<()> {
    let pkgver = match version.split_once('-') {
        Some((pkgver, _)) => pkgver,
        None => version,
    };
    let subver = match version
        .split_once('-')
        .map(|(_, subver)| format!("-{subver}"))
    {
        Some(value) => value,
        None => EMPTY_SUBVER_DEFAULT,
    };
    let pkgbuild = format!(
        "# Maintainer: dax\n\
         # Maintainer: adam\n\
         \n\
         pkgname='jekko-bin'\n\
         pkgver={pkgver}\n\
         _subver={subver}\n\
         options=('!debug' '!strip')\n\
         pkgrel=1\n\
         pkgdesc='The AI coding agent built for the terminal.'\n\
         url='https://github.com/neverhuman/jekko'\n\
         arch=('aarch64' 'x86_64')\n\
         license=('MIT')\n\
         provides=('jekko')\n\
         conflicts=('jekko')\n\
         depends=('ripgrep')\n\
         \n\
         source_aarch64=(\"${{pkgname}}_${{pkgver}}_aarch64.tar.gz::https://github.com/neverhuman/jekko/releases/download/v${{pkgver}}${{_subver}}/jekko-linux-arm64.tar.gz\")\n\
         sha256sums_aarch64=('{arm64_sha}')\n\
         \n\
         source_x86_64=(\"${{pkgname}}_${{pkgver}}_x86_64.tar.gz::https://github.com/neverhuman/jekko/releases/download/v${{pkgver}}${{_subver}}/jekko-linux-x64.tar.gz\")\n\
         sha256sums_x86_64=('{x64_sha}')\n\
         \n\
         package() {{\n\
           install -Dm755 ./jekko \"${{pkgdir}}/usr/bin/jekko\"\n\
         }}\n"
    );

    let pkg = "jekko-bin";
    let aur_dir = repo_root.join("dist").join(format!("aur-{pkg}"));
    let _ = fs::remove_dir_all(&aur_dir);
    run_checked(
        Command::new("git")
            .args(["clone", &format!("ssh://aur@aur.archlinux.org/{pkg}.git")])
            .arg(&aur_dir),
        "git clone aur repo",
    )?;
    run_checked(
        Command::new("git")
            .args(["checkout", "master"])
            .current_dir(&aur_dir),
        "git checkout master",
    )?;
    fs::write(aur_dir.join("PKGBUILD"), pkgbuild)
        .with_context(|| format!("write {}", aur_dir.join("PKGBUILD").display()))?;
    let srcinfo = Command::new("makepkg")
        .args(["--printsrcinfo"])
        .current_dir(&aur_dir)
        .output()
        .with_context(|| "run makepkg --printsrcinfo")?;
    if !srcinfo.status.success() {
        bail!(
            "makepkg --printsrcinfo failed with status {}",
            srcinfo.status
        );
    }
    fs::write(aur_dir.join(".SRCINFO"), &srcinfo.stdout)
        .with_context(|| format!("write {}", aur_dir.join(".SRCINFO").display()))?;
    run_checked(
        Command::new("git")
            .args(["add", "PKGBUILD", ".SRCINFO"])
            .current_dir(&aur_dir),
        "git add aur metadata",
    )?;
    let has_changes = !Command::new("git")
        .args(["diff", "--cached", "--quiet"])
        .current_dir(&aur_dir)
        .status()
        .with_context(|| "run git diff --cached --quiet")?
        .success();
    if has_changes {
        run_checked(
            Command::new("git")
                .args(["commit", "-m", &format!("Update to v{version}")])
                .current_dir(&aur_dir),
            "git commit aur update",
        )?;
        run_checked(
            Command::new("git").args(["push"]).current_dir(&aur_dir),
            "git push aur update",
        )?;
    }
    Ok(())
}

fn update_homebrew(
    repo_root: &Path,
    version: &str,
    mac_x64_sha: &str,
    mac_arm64_sha: &str,
    arm64_sha: &str,
    x64_sha: &str,
) -> Result<()> {
    let homebrew_formula = format!(
        "# typed: false\n\
         # frozen_string_literal: true\n\
         \n\
         # This file was generated by GoReleaser. DO NOT EDIT.\n\
         class Opencode < Formula\n\
           desc \"The AI coding agent built for the terminal.\"\n\
           homepage \"https://github.com/neverhuman/jekko\"\n\
           version \"{version}\"\n\
         \n\
           depends_on \"ripgrep\"\n\
         \n\
           on_macos do\n\
             if Hardware::CPU.intel?\n\
               url \"https://github.com/neverhuman/jekko/releases/download/v{version}/jekko-darwin-x64.zip\"\n\
               sha256 \"{mac_x64_sha}\"\n\
         \n\
               def install\n\
                 bin.install \"jekko\"\n\
               end\n\
             end\n\
             if Hardware::CPU.arm?\n\
               url \"https://github.com/neverhuman/jekko/releases/download/v{version}/jekko-darwin-arm64.zip\"\n\
               sha256 \"{mac_arm64_sha}\"\n\
         \n\
               def install\n\
                 bin.install \"jekko\"\n\
               end\n\
             end\n\
           end\n\
         \n\
           on_linux do\n\
             if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?\n\
               url \"https://github.com/neverhuman/jekko/releases/download/v{version}/jekko-linux-x64.tar.gz\"\n\
               sha256 \"{x64_sha}\"\n\
               def install\n\
                 bin.install \"jekko\"\n\
               end\n\
             end\n\
             if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?\n\
               url \"https://github.com/neverhuman/jekko/releases/download/v{version}/jekko-linux-arm64.tar.gz\"\n\
               sha256 \"{arm64_sha}\"\n\
               def install\n\
                 bin.install \"jekko\"\n\
               end\n\
             end\n\
           end\n\
         end\n"
    );

    let token =
        env::var("GITHUB_TOKEN").context("GITHUB_TOKEN is required to update homebrew tap")?;
    let tap = format!("https://x-access-token:{token}@github.com/neverhuman/homebrew-tap.git");
    let tap_dir = repo_root.join("dist").join("homebrew-tap");
    let _ = fs::remove_dir_all(&tap_dir);
    run_checked(
        Command::new("git").args(["clone", &tap]).arg(&tap_dir),
        "git clone homebrew tap",
    )?;
    fs::write(tap_dir.join("jekko.rb"), homebrew_formula)
        .with_context(|| format!("write {}", tap_dir.join("jekko.rb").display()))?;
    run_checked(
        Command::new("git")
            .args(["add", "jekko.rb"])
            .current_dir(&tap_dir),
        "git add homebrew formula",
    )?;
    let has_changes = !Command::new("git")
        .args(["diff", "--cached", "--quiet"])
        .current_dir(&tap_dir)
        .status()
        .with_context(|| "run git diff --cached --quiet")?
        .success();
    if has_changes {
        run_checked(
            Command::new("git")
                .args(["commit", "-m", &format!("Update to v{version}")])
                .current_dir(&tap_dir),
            "git commit homebrew update",
        )?;
        run_checked(
            Command::new("git").args(["push"]).current_dir(&tap_dir),
            "git push homebrew update",
        )?;
    }
    Ok(())
}

fn sha256(path: &Path) -> Result<String> {
    let bytes = fs::read(path).with_context(|| format!("read {}", path.display()))?;
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    Ok(hex::encode(hasher.finalize()))
}

fn run_checked(cmd: &mut Command, label: &str) -> Result<()> {
    let status = cmd.status().with_context(|| format!("run {label}"))?;
    if !status.success() {
        bail!("{label} failed with status {status}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha256_matches_expected_vector() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("foo");
        fs::write(&path, b"hello").unwrap();
        assert_eq!(
            sha256(&path).unwrap(),
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
    }
}
