//! Build script that embeds the Drizzle migration journal into the binary.
//!
//! Scans `db/migrations/<timestamp>_<label>/migration.sql` relative to the
//! workspace root and generates a `migrations.gen.rs` file (placed in
//! `OUT_DIR`) containing a `MIGRATIONS` slice the crate `include!`s.
//!
//! The hash is computed with the established migration algorithm (SHA-256 of
//! the raw SQL text, lower-case hex) so existing databases open cleanly under
//! Rust.

use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // crates/jekko-store -> repo root -> db/migrations
    let migrations_dir = manifest_dir
        .parent() // crates/
        .and_then(Path::parent) // repo root
        .map(|root| root.join("db").join("migrations"))
        .expect("locate db/migrations directory");

    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:rerun-if-changed={}",
        migrations_dir.to_string_lossy()
    );

    let mut entries: Vec<MigrationEntry> = Vec::new();
    let read_dir = match fs::read_dir(&migrations_dir) {
        Ok(rd) => rd,
        Err(err) => panic!(
            "failed to read migrations dir {}: {err}",
            migrations_dir.display()
        ),
    };

    for entry in read_dir {
        let entry = entry.expect("read dir entry");
        let path = entry.path();
        let file_type = entry.file_type().expect("file type");
        if !file_type.is_dir() {
            continue;
        }
        let name = match entry.file_name().into_string() {
            Ok(n) => n,
            Err(_) => continue,
        };
        let sql_path = path.join("migration.sql");
        if !sql_path.exists() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", sql_path.to_string_lossy());
        let sql = match fs::read_to_string(&sql_path) {
            Ok(s) => s,
            Err(err) => panic!("read {}: {err}", sql_path.display()),
        };
        let timestamp = migration_timestamp(&name);
        let hash = sha256_hex(&sql);
        let include_path = sql_path
            .to_string_lossy()
            .replace('\\', "/")
            .replace('"', "\\\"");
        entries.push(MigrationEntry {
            name,
            timestamp,
            hash,
            include_path,
        });
    }

    entries.sort_by(|a, b| {
        a.timestamp
            .cmp(&b.timestamp)
            .then_with(|| a.name.cmp(&b.name))
    });

    let mut generated = String::new();
    generated.push_str(
        "// Auto-generated by build.rs. Do not edit.\n\
         pub(crate) struct EmbeddedMigration {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub timestamp: i64,\n\
         \x20   pub sql: &'static str,\n\
         \x20   pub hash: &'static str,\n\
         }\n\n",
    );
    generated.push_str(&format!(
        "pub(crate) const MIGRATIONS: [EmbeddedMigration; {}] = [\n",
        entries.len()
    ));
    for entry in &entries {
        generated.push_str("    EmbeddedMigration {\n");
        generated.push_str(&format!("        name: {:?},\n", entry.name));
        generated.push_str(&format!("        timestamp: {}_i64,\n", entry.timestamp));
        generated.push_str(&format!(
            "        sql: include_str!(\"{}\"),\n",
            entry.include_path
        ));
        generated.push_str(&format!("        hash: {:?},\n", entry.hash));
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    let out_path = out_dir.join("migrations.gen.rs");
    fs::write(&out_path, generated).expect("write migrations.gen.rs");
}

struct MigrationEntry {
    name: String,
    timestamp: i64,
    hash: String,
    include_path: String,
}

fn sha256_hex(text: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(text.as_bytes());
    hex::encode(hasher.finalize())
}

/// Parse a Drizzle migration directory name into a UTC ms timestamp.
///
/// Mirrors the build-time computation from the existing build script: the prefix
/// `YYYYMMDDHHMMSS` is interpreted as `Date.UTC(year, month-1, ...)` in
/// milliseconds. Existing migration journals store that value in
/// `__drizzle_migrations.created_at`, so the Rust embedding must match exactly
/// for journal parity.
fn migration_timestamp(name: &str) -> i64 {
    if name.len() < 14 {
        return 0;
    }
    let bytes = name.as_bytes();
    let parse = |start: usize, end: usize| -> Option<i64> {
        std::str::from_utf8(&bytes[start..end])
            .ok()
            .and_then(|s| s.parse::<i64>().ok())
    };
    let year = match parse(0, 4) {
        Some(v) => v,
        None => return 0,
    };
    let month = match parse(4, 6) {
        Some(v) => v,
        None => return 0,
    };
    let day = match parse(6, 8) {
        Some(v) => v,
        None => return 0,
    };
    let hour = match parse(8, 10) {
        Some(v) => v,
        None => return 0,
    };
    let minute = match parse(10, 12) {
        Some(v) => v,
        None => return 0,
    };
    let second = match parse(12, 14) {
        Some(v) => v,
        None => return 0,
    };
    utc_millis(year, month, day, hour, minute, second)
}

fn utc_millis(year: i64, month: i64, day: i64, hour: i64, minute: i64, second: i64) -> i64 {
    // Mirrors JavaScript's `Date.UTC(year, monthIndex, day, hour, minute, second)`.
    let month_index = month - 1;
    let mut full_year = year + month_index.div_euclid(12);
    let mut m = month_index.rem_euclid(12);
    if m < 0 {
        m += 12;
        full_year -= 1;
    }
    let days_before_year = days_from_epoch_to_year(full_year);
    let days_in_year = cumulative_days_before_month(full_year, m as usize);
    let total_days = days_before_year + days_in_year + (day - 1);
    let total_seconds = total_days * 86_400 + hour * 3_600 + minute * 60 + second;
    total_seconds * 1_000
}

fn is_leap_year(year: i64) -> bool {
    (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)
}

fn cumulative_days_before_month(year: i64, month_zero_based: usize) -> i64 {
    const NORMAL: [i64; 12] = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
    const LEAP: [i64; 12] = [0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335];
    let table = if is_leap_year(year) { LEAP } else { NORMAL };
    table[month_zero_based.min(11)]
}

fn days_from_epoch_to_year(year: i64) -> i64 {
    let mut days = 0_i64;
    if year >= 1970 {
        for y in 1970..year {
            days += if is_leap_year(y) { 366 } else { 365 };
        }
    } else {
        for y in year..1970 {
            days -= if is_leap_year(y) { 366 } else { 365 };
        }
    }
    days
}
